# ここに設定した名前がActions上に表示される
name: pytest

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Run tests with pytest
    # 実行環境として `ubuntu-latest` という名前のものを選ぶ
    runs-on: ubuntu-latest
    # 複数の Python のバージョンでテストするために `strategy.matrix` を設定する
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      # 作業用ディレクトリを作成
      - name: Make Directory
        run: |
          mkdir _deploy
          echo $(ls -la)
          cd _deploy
          echo $(pws)

      # アセットをgoogle driveからコピー
      - name: Download from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: _actions_assets/dlapp_skelton.tgz
          download-to: .
          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      # アセットを解凍
      - name: Extract tgz
        run: |
          tar xvf ../dlapp_skelton.tgz
          echo $(ls -la)

      # チェックアウト先に移動
      - name: ExtractMake Directory and Extract tgz
        run: |
          cd drt
          echo $(pwd)
          echo $(ls -la)

      # リポジトリをチェックアウト
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # チェックアウト結果を確認
      - name: Echo checkout result
        run: |
          echo $(pwd)
          echo $(ls -la)

      # デプロイ用tgzを作成する
      - name: Make Deploy file
        run: |
          tar zcvf ../dhfs.tgz .
          cd ..
          echo $(pwd)
          echo $(ls -la)

      # 成果物をgoogle driveへコピーする
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: ./dhfs.tgz
          upload-to: _actions_artifacts/dhfs.tgz

          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
