# ここに設定した名前がActions上に表示される
name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build_dlapp:
    name: build dlapp using google drive assets
    # 実行環境として `ubuntu-latest` という名前のものを選ぶ
    runs-on: ubuntu-latest
    # 複数の Python のバージョンでテストするために `strategy.matrix` を設定する
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      # アセットをgoogle driveからコピー
      - name: Download assets from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: _actions_assets/dlapp_skelton.tgz
          download-to: .
          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      # 作業用ディレクトリを作成
      - name: Make package dir
        run: mkdir _deploy

      # アセットを解凍
      - name: Unarchive dlapp skelton
        run: |
          cd _deploy
          tar xvf ../dlapp_skelton.tgz

      # 確認
      - name: Check Directory Tree
        run: tree

      # リポジトリをチェックアウト
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: _deploy/drt

      # 確認
      - name: Check Directory Tree
        run: tree

      # デプロイ用tgzを作成する
      - name: Make Deploy file
        run: |
          cd _deploy/drt
          tar --exclude='.git' --exclude='.gitignore' -zcvf ../../dhfs.tgz .

      # 確認
      - name: Check Directory Tree
        run: tree

      # アップロードするdfhs.tgzへ日時を付与
      # DHFS_NAME="dhfs-${DATE_STR}.tgz"
      - name: Make artifact name
        id: step-artifact-name
        run: |
          DATE_STR=$(date "+%Y%m%d-%H%M%S")
          echo "::set-output name=DHFS_NAME::dhfs-${DATE_STR}.tgz"
          echo "$DHFS_NAME"

      # 成果物をgoogle driveへコピーする
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: ./dhfs.tgz
          upload-to: _actions_artifacts/${{ steps.step-artifact-name.outputs.DHFS_NAME }}

          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
