# ここに設定した名前がActions上に表示される
name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build_dlapp:
    name: build dlapp using google drive assets
    # 実行環境として `ubuntu-latest` という名前のものを選ぶ
    runs-on: ubuntu-latest
    # 複数の Python のバージョンでテストするために `strategy.matrix` を設定する
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      # アセットをgoogle driveからコピー
      - name: Download assets from Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: _actions_assets/dlapp_skelton.tgz
          download-to: .
          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      # 作業用ディレクトリを作成
      # アセットを解凍
      - name: Status check
        run: |
          pwd
          ls -la
          echo "mkdir _deploy"
          mkdir _deploy
          ls -la
          cd _deploy
          echo "tar xvf ../dlapp_skelton.tgz"
          tar xvf ../dlapp_skelton.tgz
          tree

      # リポジトリをチェックアウト
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: _deploy/drt

      # チェックアウト結果を確認
      - name: Echo checkout result
        run: |
          tree

      # デプロイ用tgzを作成する
      - name: Make Deploy file
        run: |
          cd _deploy/drt
          tar --exclude='.git' --exclude='.gitignore' -zcvf ../../dhfs.tgz . 
          cd ..
          tree

      # 成果物をgoogle driveへコピーする
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          upload-from: ./dhfs.tgz
          upload-to: _actions_artifacts/dhfs.tgz

          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
